version: '2.1'
services:
  ui:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    environment:
      - BALROG_ROOT_URL=https://localhost:8010
      - HOST=0.0.0.0
      - PORT=9000
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    entrypoint:
      - /bin/bash
      - --login
      - -c
      - yarn install && yarn start

volumes:
  node_modules:
